name: .NET Core

on:  
  push:
    branches:
    - release/*
      
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

      # Prepare Container
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Install NuGet client
      uses: warrenbuckley/Setup-Nuget@v1    

      # Perform Testing
    - name: Test with dotnet
      run: dotnet test src\GPS.RandomDataGeneration.sln --configuration Debug

      # Pack
    - name: Pack with dotnet
      run: dotnet pack src\GPS.RandomDataGeneration.sln --configuration Release -restore:True

      # Publish the packages
    - name: Publish to GitHub Repository
      shell: bash
      run: |
            for f in ./RandomDataGeneration/packages/*.nupkg
            do 
                curl -vX PUT -u "gatewayprogrammingschool:${{ secrets.GitHubToken }}" -F package=@$f https://nuget.pkg.github.com/gatewayprogrammingschool/
            done

      # Hold onto artifacts from the build.
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: GPS.RandomDataGenerator
        path: packages
