name: .NET

on:
  push:
    branches: [ main, master ]
  release:
    tags: 
      - v*
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    env:
      action: ${{ github.event_name }}

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
        
    - name: Setup Scoop
      run: |
        iwr -useb get.scoop.sh | iex
        scoop install gitversion
        GitVersion
        
    - name: Restore dependencies
      run: dotnet restore .\src\GPS.RandomDataGeneration.sln
      
    - name: Build Debug
      if: ${{ github.event_name != 'release' }}
      run: |
        echo "action: ${{ env.action }}"
        echo "event_name: ${{  github.event_name }}"
        dotnet build .\src\GPS.RandomDataGeneration.sln  -c Debug --no-restore 
        dotnet test .\src\GPS.RandomDataGeneration.sln  -c Debug --no-build
        
    - name: Build Release
      if: ${{ github.event_name == 'release' }}
      run: |
        echo "action: ${{ env.action }}"
        echo "event_name: ${{  github.event_name }}"
        dotnet build .\src\GPS.RandomDataGeneration.sln -c Release --no-restore 
        dotnet test .\src\GPS.RandomDataGeneration.sln -c Release --no-build
      
    - name: Publish
      if: ${{ github.event_name == 'release' }}
      run: |
        echo "action: ${{ env.action }}"
        echo "event_name: ${{  github.event_name }}"        
        $outPath = (Join-Path . -Child packages)
        dotnet pack .\src\GPS.RandomDataGeneration.sln -c Release --no-restore --include-source --no-build -o $outPath 
        
        gci $outPath\*.nupkg -ErrorAction Stop
        gci $outPath\*.snupkg -ErrorAction Stop
        
        gci $outPath\*.nupkg | forEach-Object -process {
          dotnet nuget push $_ -k "${{ secrets.NUGET_KEY }}" -s https://api.nuget.org/v3/index.json --skip-duplicate
        }
        gci $outPath\*.snupkg | forEach-Object -process {
          dotnet nuget push $_ -k "${{ secrets.NUGET_KEY }}" -s https://api.nuget.org/v3/index.json --skip-duplicate
        }
        
